# basic options
 title: James Basa
 author: James Basa
 description: First website
# email: nbasa@ucsd.edu
# twitter_username: jamesbasa
# github_username:  jamesbasa

# Build settings
markdown: kramdown
theme: minima
