# basic options
# title: James Basa
 author: James Basa
# email: nbasa@ucsd.edu
 description: First website
# twitter_username: jamesbasa
# github_username:  jamesbasa

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
