# basic options
title: James Basa
author: James Basa
description: aka Jamestar
# email: nbasa@ucsd.edu
twitter_username: jamesbasa
# github_username:  jamesbasa

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
