# basic options
title: James Basa
author: James Basa
description: B.S. in Computer Engineering <br>UC San Diego alumni
logo: /IEEE.JPG
google_analytics: UA-179509977-1
# email: 
# github_username:  jamesbasa

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
