# basic options
title: James Basa
author: James Basa
description: B.S. in Computer Engineering<br>University of California, San Diego
logo: /IEEE.JPG
# email: nbasa@ucsd.edu
# github_username:  jamesbasa

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
